### ISSUE TITLE
why?

### ISSUE THREAD

**Issue by AshKetchumPL** [Frozen-op/DISCORD-IMAGE-LOGGER#1]
its just a token grabber

**Comment by Frozen-op** [comment]
DM me on discord

**Comment by AshKetchumPL** [comment]
what's your discord?

**Comment by AshKetchumPL** [comment]
just dm me: >>ash ketchum<<#6595

**Comment by Frozen-op** [comment]
Send me yours

**Comment by AshKetchumPL** [comment]
i just did >>ash ketchum<<#6595

**Comment by AshKetchumPL** [comment]
my discord is  >>ash ketchum<<#6595 
if you dont understand

**Comment by AshKetchumPL** [comment]
u there?

**Comment by AshKetchumPL** [comment]
im gonna report this to github
